name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      PATH_PREFIX: /${GITHUB_REPOSITORY}
    defaults:
      run:
        working-directory: _site
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: yarn install

      - run: mkdir -p build/

      - run: yarn clean

      - run: npx @11ty/eleventy --pathprefix=${GITHUB_REPOSITORY#*/}

      - run: npx webpack

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: _site/build # The folder the action should deploy.
          CLEAN: true
